export { default as Content } from './content'
export { default as Header } from './header'
export { default as Hero } from './hero'
export { default as Intro } from './intro'
export { default as PortfolioSection } from './portfolio'
export { default as Contact } from './contact'
